name: Deploy Static Site

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Static Site
        run: |
          az storage blob upload-batch \
            --account-name tsazureresumestatic \
            --source frontend/ \
            --destination '$web' \
            --no-progress

