name: Deploy Static Site + API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Static Site + API
    runs-on: ubuntu-latest

    steps:
      # 1) checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Deploy front-end + API to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token:                   ${{ secrets.GITHUB_TOKEN }}
          action:                       upload

          # —— FRONTEND (already built) ——
          skip_app_build:   true
          app_location:     frontend
          output_location:  frontend

          # —— API (Functions) ——
          skip_api_build:   false
          api_location:     swa-db-connections
