name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Storage connection string
        id: get-conn
        run: |
          conn=$(az storage account show-connection-string \
            --resource-group azureresume \
            --name tsazureresumestatic \
            --query connectionString -o tsv)
          echo "AZURE_STORAGE_CONNECTION_STRING=$conn" >> $GITHUB_ENV

      - name: Clean $web container
        run: |
          az storage blob delete-batch \
            --source '$web'

      - name: Upload frontend to $web
        run: |
          az storage blob upload-batch \
            --source frontend/ \
            --destination '$web' \
            --no-progress
