name: Deploy to Azure Static Web Apps via CLI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # 1) Checkout your repo
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Login to Azure with your service principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3) Deploy frontend & API via CLI
      - name: Deploy Static Web App
        shell: bash
        run: |
          az staticwebapp upload \
            --name tzac-static-app \
            --resource-group tzac-rg \
            --source frontend/ \
            --api-location backend/ \
            --no-fail-on-empty-changes

      # 4) (Optional) Show the default hostname
      - name: Show SWA URL
        run: |
          echo "Your site is live at:"
          az staticwebapp show \
            --name tzac-static-app \
            --resource-group tzac-rg \
            --query defaultHostname \
            -o tsv
