name: Build and Deploy SWA

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"              # ← this tells the action to do an upload deploy
          app_location: "/"      # your React app folder
          api_location: "backend"       # your Functions folder
          output_location: "frontend/build"
